# train
CUDA_VISIBLE_DEVICES=0 python main_nsm.py --name CONVEXQA --model_name gnn --mode student --data_folder ConvQuestions/ --checkpoint_dir checkpoint/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 80 --word_dim 300 --kg_dim 80 --eval_every 1 --experiment_name convex_nsm --eps 0.95 --num_epoch 30 --train_KL --use_self_loop --use_inverse_relation --lr 5e-4 --q_type seq --word_emb_file word_emb_300d.npy --encode_type --reason_kb --loss_type kl

# hybrid teacher-student
CUDA_VISIBLE_DEVICES=0 python main_teacher.py --model_name gnn --teacher_type hybrid --data_folder ConvQuestions/ --checkpoint_dir checkpoint/teacher/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 80 --word_dim 300 --kg_dim 80 --eval_every 1 --experiment_name convex_hybrid_teacher --eps 0.95 --num_epoch 30 --train_KL --use_self_loop --use_inverse_relation --lr 5e-4 --q_type seq --word_emb_file word_emb_300d.npy --encode_type --reason_kb --loss_type kl --lambda_constrain 0.01 --lambda_back 0.1
CUDA_VISIBLE_DEVICES=0 python main_student.py --model_name gnn --teacher_model gnn --teacher_type hybrid --data_folder ConvQuestions/ --checkpoint_dir checkpoint/student/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 80 --word_dim 300 --kg_dim 80 --eval_every 1 --experiment_name convex_hybrid_student --eps 0.95 --num_epoch 30 --train_KL --use_self_loop --use_inverse_relation --lr 5e-4 --q_type seq --word_emb_file word_emb_300d.npy --encode_type --reason_kb --loss_type kl --load_teacher ../teacher/convex_hybrid_teacher-final.ckpt --lambda_label 0.01

# parallel teacher-student
CUDA_VISIBLE_DEVICES=0 python main_teacher.py --model_name gnn --teacher_type parallel --data_folder ConvQuestions/ --checkpoint_dir checkpoint/teacher/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 80 --word_dim 300 --kg_dim 80 --eval_every 1 --experiment_name convex_parallel_teacher --eps 0.95 --num_epoch 30 --train_KL --use_self_loop --use_inverse_relation --lr 5e-4 --q_type seq --word_emb_file word_emb_300d.npy --encode_type --reason_kb --loss_type kl --lambda_constrain 0.01 --lambda_back 0.1
CUDA_VISIBLE_DEVICES=0 python main_student.py --model_name gnn --teacher_model gnn --teacher_type parallel --data_folder ConvQuestions/ --checkpoint_dir checkpoint/student/ --batch_size 80 --test_batch_size 80 --num_step 3 --entity_dim 80 --word_dim 300 --kg_dim 80 --eval_every 1 --experiment_name convex_parallel_student --eps 0.95 --num_epoch 30 --train_KL --use_self_loop --use_inverse_relation --lr 5e-4 --q_type seq --word_emb_file word_emb_300d.npy --encode_type --reason_kb --loss_type kl --load_teacher ../teacher/convex_parallel_teacher-final.ckpt --lambda_label 0.01

